backend:
  name: github
  repo: scott-gr/oakhurst-dog-park
  branch: main

site_url: https://oakhurstdogpark.com

media_folder: content/assets/media
public_folder: /assets

collections:
  - name: blog
    label: Blog
    label_singular: Blog Post
    description: Publish new posts to the blog.
    folder: /content/blog
    editor: 
      preview: true
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description, widget: string, required: false }
      - { name: image, label: Cover Image, widget: image, required: false}
      - { name: body, label: Body, widget: markdown }

  - name: announcements
    label: Front Page Announcment
    label_singular: Announcement
    description: The announcement will appear on the home page. Edit this post to change it.
    folder: /content/announcements
    editor: 
      preview: true
    create: false #users cannot create new posts, but just edit the single post.
    delete: false #users cannot delte posts, just edit.
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description, widget: string, required: false }
      - { name: image, label: Cover Image, widget: image, required: false}
      - { name: body, label: Body, widget: markdown }

  - name: rules
    label: Rules
    label_singular: Rule
    description: Each entry will display on the Park Rules page.
    folder: /content/rules
    editor: 
      preview: true 
    create: true  # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{rulebrief}}"
    fields: #fields to complete in admin page to create a new rule entry.
      - { name: rulebrief, label: Rule Brief, widget: string, hint: This is a brief summary of the rule.}
      - { name: date, label: Date, widget: datetime, allowInput: false, default: hidden}
      - { name: category, label: Select Category, widget: select, options: ['The Basics', 'Behavior', 'COVID-19 Protocol', 'Collars and Leashes', 'Children', 'Food, Drink, and Smoking', 'Additional Guidelines'], multiple: false, hint: Use 'Additional Guidelines' for miscellaneous items.}
      - { name: description, label: Full Description, widget: markdown, hint: Expand upon the rule and give additional context.}
  
  - name: resources
    label: Resources
    label_singular: Resource
    description: Permanent Links and helpful info for dog owners.
    folder: /content/resources
    editor: 
      preview: true 
    create: true  # Allow users to create new documents in this collection
    slug: "{{name}}"
    fields: 
      - { name: name, label: Name, widget: string, hint: Name of the linked page or resources. Keep this field short.}
      - { name: date, label: Date, widget: datetime, allowInput: false}
      - { name: content, label: Content, widget: markdown, hint: Add the link and any commentary on it here.}